### ISSUE TITLE
Is the login server open source?

### ISSUE THREAD

**Issue by IdotMaster1** [ElVir-Software/minicraft-plus-online#1]

**Comment by El-Virus** [comment]
Well, the legacy one, never was, at the moment, it's not very developed yet, maybe when it's more mature it will be.

**Comment by El-Virus** [comment]
Either way, as Chris said, the purpose of the login server is to verify someone's identity. Wouldn't having multiple instances of them defeat the purpose?

**Comment by IdotMaster1** [comment]
People can contribute so if there is a security bug and someone catches it they can fix it and make a pull request

**Comment by El-Virus** [comment]
Oh, don't worry about, that, I'm pretty sure it's safe, and all data is encrypted either way...
